name: flutter_application_practice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
freezed_annotation: ^3.1.0
hooks_riverpod: ^3.0.3
flutter_hooks: ^0.21.3+1
riverpod_annotation: ^3.0.3
json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^5.0.0
build_runner: ^2.10.1
freezed: ^3.2.3
riverpod_generator: ^3.0.3
json_serializable: ^6.11.1

flutter:
  uses-material-design: true
